Wagtail 5.0
torchbox-forks/wagtail_blocks pull request #2
Opened 2023-07-25 08:57 UTC by nickmoreton

2023-07-26 13:16 UTC, victoriachan requested changes
Looks good in general. 

Just a tiny change needed on installation.md to change `wagtailfontawesome` to `wagtailfontawesomesvg`.

I have also tested locally on a wagtail 5 build, and it works fine.

2023-07-26 13:16 UTC, victoriachan commented on docs/installation.md
>  'wagtailfontawesome',
should change to `'wagtailfontawesomesvg',`.

2023-07-26 13:45 UTC, nickmoreton commented on docs/installation.md
>  'wagtailfontawesome',
@victoriachan Nicely spotted, thanks. I have updated it.

2023-07-26 14:54 UTC, victoriachan approved these changes
Look good!

2023-10-24 09:20 UTC, nickmoreton commented
This branch has been merged by the maintainer so closing this PR

2023-10-24 09:20 UTC, closed without merging